name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "node@node24"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        showcase:
          - "ai/slackbot-mcp-client/no-auth"
          - "ai/slackbot-mcp-client/rich-responses/mcp-apps"
          - "ai/slackbot-mcp-client/slack-identity"
          - "block-kit"
          - "methods"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Run tests
        shell: bash
        run: |
          shopt -s globstar
          export BASHOPTS npm_config_script_shell=bash
          cd "${{ matrix.showcase }}"
          npm install
          npm run lint
          npm run check
          npm test --if-present
